#!/bin/csh

echo "Pool to operate on: "
set pool = $<
echo "Snapshot to rollback to: "
set rollback2 = $<
if ( "$pool" == "" || "$rollback2" == "" ) then
	echo "You didn't give enough inputs"
	exit 1
else
	foreach zf ( `zfs list -rH -o name -t filesystem $pool` )
		zfs rollback $zf@$rollback2
		if ( "$status" != 0 ) then
			echo "Error rolling back to $rollback2 snapshot"
			exit 1
		endif
	end
	echo "Rollback is successful."
endif

exit 0
